spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://PROJECT-SERVICE
          predicates:
            - Path= /projects/**
        - id: r2
          uri: lb://TASK-SERVICE
          predicates:
            - Path= /tasks/**